name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install Flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get


      # Set the name of the artifact to be uploaded
      - name: Deploy Flutter web app to github pages (removing large assets/NOTICES file)
        uses: AlienKevin/flutter-gh-pages@v11
